### ISSUE TITLE
test_indent_render is failing

### ISSUE THREAD

**Issue by pbauer** [starzel/starzel.snippets#1]
One test is failing:

```
Running tests at level 1
Running starzel.snippets.testing.SnippetsLayer:Integration tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.247 seconds.
  Set up plone.app.testing.layers.PloneFixture in 10.818 seconds.
  Set up starzel.snippets.testing.SnippetsLayer in 1.090 seconds.
  Set up starzel.snippets.testing.SnippetsLayer:Integration in 0.000 seconds.
  Running:
 test_get_code (starzel.snippets.tests.test_api.TestAPI) (0.116 s)
 test_get_code_custom_expression (starzel.snippets.tests.test_api.TestAPI) (0.099 s)
 test_get_ref_form_snippet (starzel.snippets.tests.test_linkintegrity.TestTransform) (0.193 s)
 test_customize_render_expression (starzel.snippets.tests.test_transform.TestTransform) (0.099 s)
 test_indent_render (starzel.snippets.tests.test_transform.TestTransform) (0.101 s)


Failure in test test_indent_render (starzel.snippets.tests.test_transform.TestTransform)
Traceback (most recent call last):
  File "/Users/philip/workspace/buildout.python/parts/opt/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/Users/philip/workspace/uhlmann/src-mrd/starzel.snippets/src/starzel/snippets/tests/test_transform.py", line 59, in test_indent_render
    self.assertTrue('<h3>Foobar 1' in result)
  File "/Users/philip/workspace/buildout.python/parts/opt/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true


 test_replace_tag (starzel.snippets.tests.test_transform.TestTransform) (0.101 s)
 test_should_include_container (starzel.snippets.tests.test_transform.TestTransform) (0.099 s)
 test_should_include_data_attributes_on_source (starzel.snippets.tests.test_transform.TestTransform) (0.101 s)
  Ran 8 tests with 1 failures and 0 errors in 0.977 seconds.
Tearing down left over layers:
  Tear down starzel.snippets.testing.SnippetsLayer:Integration in 0.000 seconds.
  Tear down starzel.snippets.testing.SnippetsLayer in 0.004 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.084 seconds.
  Tear down plone.testing.z2.Startup in 0.008 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.001 seconds.

Tests with failures:
   test_indent_render (starzel.snippets.tests.test_transform.TestTransform)
```

**Comment by vangheem** [comment]
Pushed fix.
